const API = "http://127.0.0.1:5000";
let latest=null; const $=id=>document.getElementById(id);
async function checkAPI(){try{const r=await fetch(`${API}/api/health`);if(!r.ok)throw 0;$("apiStatus").textContent="● API online";$("apiStatus").className="online"}catch{$("apiStatus").textContent="● API offline";$("apiStatus").className="offline"}}
function err(m){$("error").textContent=m;$("error").classList.remove("hidden")}
async function gather(){const target=$("target").value.trim();if(!target)return err("Enter an authorized target first.");$("error").classList.add("hidden");$("results").classList.add("hidden");$("loading").classList.remove("hidden");$("scan").disabled=true;$("scan").textContent="RUNNING…";try{const r=await fetch(`${API}/api/recon`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target})});const d=await r.json();if(!r.ok)throw Error(d.error||"Backend error");latest=d;render(d)}catch(e){err(`Recon failed: ${e.message}. Start the Flask backend on port 5000.`)}finally{$("loading").classList.add("hidden");$("scan").disabled=false;$("scan").textContent="RECON"}}
function render(d){const records=d.dns?.records||{};$("targetName").textContent=d.target;$("ipCount").textContent=(d.dns?.resolved_ips||[]).length;$("dnsCount").textContent=Object.values(records).reduce((n,a)=>n+a.length,0);$("httpStatus").textContent=d.http?.status_code??"—";$("rdap").textContent=d.rdap?.available?"AVAILABLE":"UNAVAILABLE";$("dns").textContent=JSON.stringify(d.dns,null,2);$("http").textContent=JSON.stringify(d.http,null,2);$("rdapData").textContent=JSON.stringify(d.rdap,null,2);$("results").classList.remove("hidden");$("results").scrollIntoView({behavior:"smooth"})}
async function ask(){const message=$("prompt").value.trim(),target=$("target").value.trim();if(!message)return;addMsg(message,"user");$("prompt").value="";try{const r=await fetch(`${API}/api/assistant`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,target})});const d=await r.json();if(!r.ok)throw Error(d.error||"Assistant error");addMsg(d.reply,"bot")}catch(e){addMsg(`Assistant unavailable: ${e.message}`,"bot")}}
function addMsg(text,type){const el=document.createElement("div");el.className=`msg ${type}`;el.textContent=text;$("chat").appendChild(el);$("chat").scrollTop=$("chat").scrollHeight}
$("scan").addEventListener("click",gather);$("target").addEventListener("keydown",e=>{if(e.key==="Enter")gather()});$("ask").addEventListener("click",ask);$("prompt").addEventListener("keydown",e=>{if(e.key==="Enter")ask()});$("copy").addEventListener("click",async()=>{if(!latest)return;await navigator.clipboard.writeText(JSON.stringify(latest,null,2));$("copy").textContent="COPIED";setTimeout(()=>$("copy").textContent="Copy JSON",1200)});checkAPI();
